root: true
parser: '@typescript-eslint/parser'
env:
  browser: false
  node: true
  es2021: true
plugins:
  - '@typescript-eslint'
  - sonarjs
  - prettier
extends:
  - prettier
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:sonarjs/recommended
  - plugin:import/recommended
  - plugin:jsdoc/recommended-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
ignorePatterns:
  - '@types/**'
settings:
  # uses 'eslint-import-resolver-foo':
  import/resolver:
    typescript: {}
rules:
  # Override default settings
  import/no-unresolved:
    - 2
    - commonjs: true
      amd: true
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  prettier/prettier: 2
  default-case: 2
  no-fallthrough: 2
  '@typescript-eslint/naming-convention':
    - error
    - selector: enumMember
      format:
        - UPPER_CASE
    - selector: variable
      format:
        - camelCase
    - selector: variable
      modifiers:
        - const
      format:
        - camelCase
        - UPPER_CASE
        - PascalCase
    # @ToDo fix below rule
    # - selector: variable
    #   modifiers:
    #     - let
    #   format:
    #     - camelCase
    - selector: classMethod
      format:
        - camelCase
      leadingUnderscore: allow
  '@typescript-eslint/no-unused-vars':
    - error
    - args: after-used
      argsIgnorePattern: ^_
  eqeqeq: 2 # Refer https://eslint.org/docs/rules/eqeqeq
  no-console: 2 # Refer https://eslint.org/docs/rules/no-console
  max-lines:
    - error
    - max: 300
      skipBlankLines: true
      skipComments: true
  max-statements:
    - error
    - 10
    - ignoreTopLevelFunctions: true
  max-depth:
    - error
    - 4
  max-lines-per-function:
    - error
    - max: 50
      skipBlankLines: true
      skipComments: true
  max-nested-callbacks:
    - error
    - max: 10
  max-params:
    - error
    - max: 3
  complexity:
    - error
    - 2
  curly:
    - error
    - all
  no-unneeded-ternary: 2 # Refer https://eslint.org/docs/rules/no-unneeded-ternary
  no-nested-ternary: 2 # Refer https://eslint.org/docs/rules/no-nested-ternary
  '@typescript-eslint/no-unnecessary-type-assertion': 2 # Refer https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-type-assertion.md
  '@typescript-eslint/consistent-type-assertions': # Refer https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-assertions.md
    - error
    - assertionStyle: as
      objectLiteralTypeAssertions: never
  camelcase: # Refer https://eslint.org/docs/rules/camelcase
    - error
    - properties: always
      ignoreDestructuring: false
      ignoreImports: false
      ignoreGlobals: false
      allow:
        - ''
  import/no-anonymous-default-export:
    - 2
    - allowArray: false
      allowArrowFunction: false
      allowAnonymousClass: false
      allowAnonymousFunction: false
      allowCallExpression: true
      allowNew: false
      allowLiteral: false
      allowObject: false
  sort-imports:
    - 2
    - ignoreCase: false
      ignoreDeclarationSort: false
      ignoreMemberSort: false
      memberSyntaxSortOrder:
        - none
        - all
        - multiple
        - single
      allowSeparatedGroups: false
  no-restricted-imports: 0
  '@typescript-eslint/no-restricted-imports':
    - 2
    - patterns
      - "!./*"
      - "!../*"
  comma-dangle:
    - error
    - arrays: only-multiline
      objects: only-multiline
      imports: only-multiline
      exports: only-multiline
      functions: only-multiline
