arrowParens: avoid
semi: false
tabWidth: 2
singleQuote: true
bracketSpacing: true
trailingComma: true
overrides:
  - files: 'docs/*.md'
    options:
      printWidth: 60
  - files: '*.js'
    options:
      parser: flow