version: '3.9'
services:
  api:
    image: anushshukla/express-ts-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: on-failure:3
