name: CI

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.15.1']
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: clone submodule
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SRE_REPO_TOKEN }}
          submodules: recursive
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      # @ToDo check if below command is required
      - name: Yarn Install global
        run: yarn global add @nestjs/cli
      - name: ESLint
        run: npm run lint
      - name: Build
        run: npm run build
